### ISSUE TITLE
请问服务列表用的是什么通信方式？

### ISSUE THREAD

**Issue by hitomichann** [PICOF/YusamiBot#1]
新年好！我昨天接触了ChatGpt的qqbot，觉得很有意思，无意中发现了yusamibot，想试着更新成这个，但是缺乏相关知识，不太懂应该怎么操作。
我按照cqhttp的[官方文档](https://github.com/Mrs4s/go-cqhttp/blob/master/docs/config.md)尝试了列出的所有连接服务，但似乎都没有成功配置，这是我的config：
```yaml
 - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://127.0.0.1:8081
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
cqhttp显示如下：
```
 [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8081
[2023-01-01 18:47:00] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8081 时出现错误: websocket: bad handshake
```
yusamibot显示如下：
```
[GIN-debug] Listening and serving HTTP on :8081
[GIN] 2023/01/01 - 18:48:00 | 404 |            0s |       127.0.0.1 | GET      "/"
```

其他的通信方式显示的是使用了过时的配置方法。
方便的话可以告诉我一下应该怎么操作吗，谢谢！
